# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abhishek Devarajan
title: Math & Statistics Researcher
email: abhishekdevarajan@gmail.com
website: www.github.com/ABeeShake

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
#github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ABeeShake
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! My name is Abhishek (A-Bee-Shake) Devarajan and I am a fourth year Math & Statistics student at UC Irvine. As an undergraduate, I have participated in multiple research projects ranging from Convex Optimization to Analyzing Renaissance era texts. In terms of future work, I hope to continue researching topics such as machine learning and optimization. I am also eager to apply machine learning methods to problems in the social sciences.
  
  Currently, I am using this webpage to host the papers that I have written. Later on, when I have more free time, I hope to turn the site into a more complete online portfolio.

content:
  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Predicting Bank Failure
        link: github.com/ABeeShake/Papers/blob/main/Banking_Failures_Report.pdf
        # link_text: Project Website
       # additional_links:
        #  - title:  sproogen/modern-resume-theme
         #   icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
         # 
        description: | # this will include new lines to allow paragraphs
          This paper was written for the CSBS Data Analytics Competition (2021). My teammates and I ended up winning 1st place!
      - layout: top-middle
        title: Using Reproducing Kernel Hilbert Spaces to Improve Support Vector Machines
        link: github.com/ABeeShake/Papers/blob/main/RKHS_Paper_Final.pdf
        # link_text: Project Website
       # additional_links:
        #  - title:  sproogen/modern-resume-theme
         #   icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        #quote: >
         # 
        description: | # this will include new lines to allow paragraphs
          I wrote this paper for my Math 195W- Mathematical Writing course. You can consider this a "senior thesis" of sorts.
         

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Hiking
      - Sewing
      - Making Music
      - Skateboarding

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
